/* fetch photos constants */
export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';
export const ADD_COMMENT = 'ADD_COMMENT';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCESS = 'CREATE_USER_SUCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

