/* fetch photos constants */
export const FETCH_PHOTOS_START = 'FETCH_PHOTOS_START';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAILURE = 'FETCH_PHOTOS_FAILURE';

//fetch a photo 
export const FETCH_PHOTO_START = 'FETCH_PHOTO_START';
export const FETCH_PHOTO_SUCCESS = 'FETCH_PHOTO_SUCCESS';
export const FETCH_PHOTO_FAILURE = 'FETCH_PHOTO_FAILURE';

//Upload a photo 
export const UPLOAD_PHOTO_START = 'UPLOAD_PHOTO_START';
export const UPLOAD_PHOTO_FAIL = 'UPLOAD_PHOTO_FAIL';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCESS';

// auth user signup constants
export const SIGNUP_USER_START = 'SIGNUP_USER_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

// auth user signin
export const SIGNIN_USER_START = 'SIGNIN_USER_START';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';

//auth user signout
export const SIGNOUT_USER_START =   'SIGNOUT_USER_START';
export const SIGNOUT_USER_SUCCESS = 'SIGNOUT_USER_SUCCESS';
export const SIGNOUT_USER_FAILURE = 'SIGNOUT_USER_FAILURE';

//FETCH USER
export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

//comments
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';

//like Photos
export const LIKE_PHOTO = 'LIKE_PHOTO';
export const UNLIKE_PHOTO = 'UNLIKE_PHOTO';
export const ADD_LIKE_START = 'ADD_LIKE_START';
export const ADD_LIKE_SUCESS = 'ADD_LIKE_SUCESS';
export const ADD_LIKE_FAIL = 'ADD_LIKE_FAIL';
export const UPDATE_LIKE = 'UPDATE_LIKE';